name: grafana-cloud-docker-alloy-poc
services:
  alloy:
    image: grafana/alloy:latest
    restart: always
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro
      - ./alloy:/var/lib/alloy/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    restart: always
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    cap_add:
      - SYS_TIME
    volumes:
      - '/:/host:ro,rslave'
